######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 23 03:59:15 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3
QMAKE_LFLAGS_RELEASE += -O3

# Input
SOURCES += battery_overlay.cpp

RESOURCES = resources.qrc

QT += gui
QT += widgets
