######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 23 03:59:15 2023
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += battery_overlay.cpp
